name: Test pipeline

on:
  push:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Test mensaje
        run: |
          echo "hola pipeline"
          echo "Deploy ejecutado"